2.x
koshi8bit/nsu-sdt2020 pull request #2
Opened 2020-10-23 06:50 UTC by koshi8bit

2020-10-30 22:36 UTC, shishkin-pavel requested changes
давай всё лишнее убирать, а?

2020-10-30 22:36 UTC, shishkin-pavel commented on 2-2-old.clj
> +(ns lab1.core
это же просто файлик с мусором?

2020-10-30 22:36 UTC, shishkin-pavel commented on 2-2.clj
> +(defn get-integrator [f begin step]
стоит проверить, это не считает интеграл и может быть сломано

2020-11-19 06:13 UTC, shishkin-pavel approved these changes

2020-11-20 19:15 UTC, shishkin-pavel requested changes

2020-11-20 19:15 UTC, shishkin-pavel commented on 2-2.clj
> +                (list begin 0))]
почему начинаем с begin?

2020-11-20 19:15 UTC, shishkin-pavel commented on 2-2.clj
> +            (first (nth ls (/ k step)))
хочется ещё прибавить неполный кусочек трапеции (если правая граница не точно попадает на шаг)

2020-11-23 18:28 UTC, koshi8bit commented on 2-2.clj
> +                (list begin 0))]
делал типа "универсально", чтоб можно было с любого числа начать. Законстантил от нуля

2020-11-23 18:28 UTC, koshi8bit commented on 2-2.clj
> +            (first (nth ls (/ k step)))
сделал

2020-11-27 20:25 UTC, shishkin-pavel commented on 2-2.clj
> +                (list begin 0))]
проблема была в другом
начинать-то можно с чего угодно, но аккумулятор должен начинаться с нуля

2020-11-28 00:42 UTC, koshi8bit commented on 2-2.clj
> +                (list begin 0))]
сейчас аккум с нуля начинается

2020-11-28 03:39 UTC, shishkin-pavel approved these changes

2020-12-04 16:45 UTC, merged