3.x
koshi8bit/nsu-sdt2020 pull request #3
Opened 2020-11-21 03:26 UTC by koshi8bit

2020-11-27 20:23 UTC, shishkin-pavel requested changes

2020-11-27 20:23 UTC, shishkin-pavel commented on 3-1.clj
> +(defn split-by-threads [threads coll]
немного не ту задачу решаем, ну да ладно (было достаточно просто распилить на блоки по `n` задач)

2020-11-27 20:23 UTC, shishkin-pavel commented on 3-2.clj
> +        (map #(partition-my chunkk %))
кажется, можно сделать проще и понятнее?

2020-11-27 20:23 UTC, shishkin-pavel commented on 3-2.clj
> +        (apply concat)
map apply concat apply concat должны достаточно аккуратно свернуться в какие-то mapcat

2020-11-27 20:23 UTC, shishkin-pavel commented on 3-2.clj
> +        (map deref)
этот pmap не pmap, т.к. возвращает последовательность последовательностей элементов (а хочется последовательность элементов)

2020-11-28 00:34 UTC, koshi8bit commented on 3-2.clj
> +        (map deref)
(pmap-my count '((1 2 3) (4) (5 6))) ;; (3 1 2)
(pmap-my even? '(1 2 3 4 5 6 7)) ;; (false true false true false true false)

Все же правильно отрабатывает? Что не так?

2020-11-28 00:44 UTC, koshi8bit commented on 3-2.clj
> +        (map deref)
(pmap-my #(map inc %) '((1 2 3 4) (5) (6 7))) ;; ((2 3 4 5) (6) (7 8))

2021-01-09 20:41 UTC, shishkin-pavel approved these changes
вроде ок

2021-01-09 20:41 UTC, shishkin-pavel commented on 3-1.clj
> +        (map #(future (f %)) coll)
кажется, было бы лучше `doall` пихнуть сюда, а не на стороне использования pmap добавлять

2021-01-10 18:21 UTC, merged